default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: energy_tool_dev
  username: <%= ENV['DB_DEV_USERNAME'] %>
  password: <%= ENV['DB_DEV_PASSWORD'] %>


test:
  <<: *default
  host: localhost
  database: energy_tool_test
  username: <%= ENV['DB_DEV_USERNAME'] %>
  password: <%= ENV['DB_DEV_PASSWORD'] %>
